[build]
  command = "npm run build:ssr"
  publish = "dist/riu-frontend-matias-pascual/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# Redirección para SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200